# Generated by Django 4.2 on 2023-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='dfgfff', upload_to=''),
            preserve_default=False,
        ),
    ]
